-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public.answer
(
    "idAnswer" integer NOT NULL,
    "textAnswer" character(500)[] NOT NULL,
    "timeAnswer" timestamp without time zone NOT NULL,
    PRIMARY KEY ("idAnswer")
);

CREATE TABLE public.keyword
(
    "idKeyword" integer NOT NULL,
    "nameKeyword" character(45)[] NOT NULL,
    PRIMARY KEY ("idKeyword")
);

CREATE TABLE public.question
(
    "idQuestion" integer NOT NULL,
    "textQuestion" character(500)[] NOT NULL,
    "timeQuestion" timestamp without time zone NOT NULL,
    PRIMARY KEY ("idQuestion")
);

CREATE TABLE public."user"
(
    "idUser" integer NOT NULL,
    "firstName" character(45)[] NOT NULL,
    "lastName" character(45)[] NOT NULL,
    email character(45)[] NOT NULL,
    username character(45)[] NOT NULL,
    password character(45)[] NOT NULL,
    PRIMARY KEY ("idUser")
);

ALTER TABLE public.answer
    ADD FOREIGN KEY ("idAnswer")
    REFERENCES public."user" ("idUser")
    NOT VALID;


ALTER TABLE public.question
    ADD FOREIGN KEY ("idQuestion")
    REFERENCES public."user" ("idUser")
    NOT VALID;


ALTER TABLE public.keyword
    ADD FOREIGN KEY ("idKeyword")
    REFERENCES public.question ("idQuestion")
    NOT VALID;


ALTER TABLE public.answer
    ADD FOREIGN KEY ("idAnswer")
    REFERENCES public.question ("idQuestion")
    NOT VALID;

END;
